#!/bin/sh
set -eu
case ${1:-} in
    ""|--check) [ "$#" -le 1 ] ;;
    *) echo "usage: sh scripts/notices.sh [--check]" >&2; exit 2 ;;
esac
mode=${1:-}
cd "$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
export LC_ALL=C
cargo_home=${CARGO_HOME:-$HOME/.cargo}
rust_doc=$(rustc --print sysroot)/share/doc/rust
mkdir -p target
work=$(mktemp -d target/notices.XXXXXX)
cargo tree --locked --target x86_64-unknown-linux-musl -e normal --prefix none > "$work/tree"
awk '$1 != "slotr" {sub(/^v/, "", $2); print $1, $2}' "$work/tree" | sort -u > "$work/crates"
{
    printf 'Third-party notices for slotr (x86_64-unknown-linux-musl)\n'
    printf 'Generated by scripts/notices.sh from the locked target dependency tree.\n'
    printf 'MIT is selected where offered; additional required notices follow.\n\n'
    while read -r name version; do
        set -- "$cargo_home"/registry/src/*/"$name-$version"
        [ "$#" -eq 1 ] && [ -f "$1/Cargo.toml" ] || {
            echo "slotr: missing or ambiguous cached crate $name $version" >&2; exit 1;
        }
        crate=$1
        license=$(sed -n 's/^license = "\([^"]*\)"$/\1/p' "$crate/Cargo.toml")
        case $license in
            MIT|'MIT OR Apache-2.0'|'Apache-2.0 OR MIT'|'Unlicense OR MIT'|\
            'Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT'|\
            '(MIT OR Apache-2.0) AND Unicode-3.0') ;;
            *) echo "slotr: review licence for $name $version: $license" >&2; exit 1 ;;
        esac
        printf '=== %s %s ===\nLicense: %s\n\n' "$name" "$version" "$license"
        if [ -f "$crate/LICENSE-MIT" ]; then
            cat "$crate/LICENSE-MIT"
        else
            cat "$crate/LICENSE"
        fi
        if [ -f "$crate/COPYRIGHT" ]; then
            printf '\n'; cat "$crate/COPYRIGHT"
        fi
        case $license in
            *'AND Unicode-3.0') printf '\n'; cat "$crate/LICENSE-UNICODE" ;;
        esac
        printf '\n\n'
    done < "$work/crates"
    printf '=== Rust standard library %s ===\nLicense: MIT OR Apache-2.0\n\n' "$(rustc --version | cut -d' ' -f2)"
    sed -n '/<h2 id="longer-version">/,/<h2 id="in-tree-files">/p' "$rust_doc/COPYRIGHT-library.html" |
        sed '/^<h2 /d; s/<[^>]*>//g'
    sed -n 's/.*<p><b>Copyright:<\/b> \([^<]*\)<\/p>.*/Copyright: \1/p' "$rust_doc/COPYRIGHT-library.html" | sort -u
    printf '\n'; cat "$rust_doc/licenses/MIT.txt"
    printf '\nUnicode-3.0 licence text (Rust standard library Unicode data):\n\n'
    cat "$rust_doc/licenses/Unicode-3.0.txt"
    printf '\nApache-2.0 licence text (Rust standard library alternative):\n\n'
    cat "$rust_doc/licenses/Apache-2.0.txt"
    printf '\n\n=== musl libc ===\nLicense: MIT\n'
    printf 'Source: https://git.musl-libc.org/cgit/musl/plain/COPYRIGHT\n'
    printf 'Standard musl MIT notice; the installed toolchain has no musl COPYRIGHT file.\n\n'
    cat <<'MUSL'
Copyright © 2005-2020 Rich Felker, et al.

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
MUSL
} > "$work/notices"
if grep -Eq '/home/|/Users/|/mnt/' "$work/notices" || grep -Fq "$(id -un)" "$work/notices"; then
    echo "slotr: notices contain a builder path or login name" >&2
    exit 1
fi
if [ "$mode" = --check ]; then
    cmp THIRD-PARTY-NOTICES "$work/notices" || {
        echo "slotr: run sh scripts/notices.sh to refresh THIRD-PARTY-NOTICES" >&2; exit 1;
    }
else
    cp "$work/notices" THIRD-PARTY-NOTICES
fi
